---
env:
  AWS_DEFAULT_REGION: ap-southeast-2

steps:
  - label: ":docker: oculo/oculo Vulnerability Scan"
    plugins:
      - ecr#v1.2.0:
          login: true
          account_ids: "644358627301"
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::644358627301:role/role-sts-oculo-continuous-integration"
      - thedyrt/change-directory#v0.1.1:
          cd: ./ecr-vulnerability-scanning/vuln-scanning
      - docker-compose#v3.0.0:
          run: infrastructure_tools
          env:
            - OCULO_BUILDKITE_BUILD_NUMBER
            - ECR_REPOSITORY_NAME=oculo/oculo
  
  - label: ":docker: oculo/oculo-nginx Vulnerability Scan"
    plugins:
      - ecr#v1.2.0:
          login: true
          account_ids: "644358627301"
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::644358627301:role/role-sts-oculo-continuous-integration"
      - thedyrt/change-directory#v0.1.1:
          cd: ./ecr-vulnerability-scanning/vuln-scanning
      - docker-compose#v3.0.0:
          run: infrastructure_tools
          env:
            - OCULO_BUILDKITE_BUILD_NUMBER
            - ECR_REPOSITORY_NAME=oculo/oculo-nginx
