template_path: .compiled-stack.yaml

stack_name: ecr-vulnerability-scanning

parameters:
  BuildkiteSecurityGroupId: sg-019ed1d65f54a2c00
  VpcId: "vpc-65745902"
  SubnetId: subnet-184e5b7f
  KeyName: services-au-june-2019
