---
steps:
  - name: ":terraform: Plan"
    command: ".buildkite/bin/plan"
    agents:
      - queue=native

  - wait

  - name: ":terraform: Apply"
    command: ".buildkite/bin/apply"
    agents:
      - queue=native

  - wait

  - name: ":secret: Upload"
    command: ".buildkite/bin/upload-secrets"
    agents:
      - queue=native
