env:
  AWS_STACK_NAME: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
  AWS_STACK_QUEUE_NAME: "testqueue-${BUILDKITE_BUILD_NUMBER}"

steps:
  - name: ":docker: Build Agent"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker-compose#v1.5.2:
        build: agent
        image-repository: 172840064832.dkr.ecr.us-east-1.amazonaws.com/elastic-stack-executor

  - name: ":docker: Build Executor"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker-compose#v1.5.2:
        build: executor
        image-repository: 172840064832.dkr.ecr.us-east-1.amazonaws.com/elastic-stack-agent

  - wait

  # - name: ":bash: Unit tests"
  #   agents:
  #     queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
  #   plugins:
  #     docker-compose#v1.5.2:
  #       run: unit-tests
  #       config: docker-compose.unit-tests.yml

  # - wait
  # - name: ":cloudformation: Launch"
  #   command: .buildkite/steps/test.sh
  #   agents:
  #     queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
  #   artifact_paths:
  #     - "build/*.json"
  #     - "build/*.yml"

  # - wait
  # - name: ":buildkite: Instance test"
  #   command: "/usr/local/bin/bats --pretty tests/"

  #   timeout_in_minutes: 5
  #   agents:
  #     stack: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
  #     queue: "testqueue-${BUILDKITE_BUILD_NUMBER}"

  # - wait
  # - name: ":cloudformation: :rocket:"
  #   command: .buildkite/steps/publish.sh
  #   agents:
  #     queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
  #   artifact_paths: "templates/mappings.yml;build/aws-stack.json;build/aws-stack.yml"
  #   concurrency_group: "aws-stack-publish"
  #   concurrency: 1

  # - wait
  # - name: "Cleanup"
  #   command: .buildkite/steps/cleanup.sh
  #   agents:
  #     queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
