env:
  AWS_STACK_NAME: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
  AWS_STACK_QUEUE_NAME: "testqueue-${BUILDKITE_BUILD_NUMBER}"

steps:
  - name: "Run linting on shell scripts"
    command: .buildkite/steps/lint.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - label: ":bash: :hammer:"
    command: "bats tests/unit"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker-compose#v1.3.2:
        run: tests

  - wait
  - command: .buildkite/steps/packer.sh
    name: "Build packer image"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - command: .buildkite/steps/test.sh
    name: "Launch :cloudformation: stack"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths:
      - "build/*.json"
      - "build/*.yml"

  - wait
  - command: "/usr/local/bin/bats --pretty tests/instance"
    name: "Run tests on :buildkite: agent"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-${BUILDKITE_BUILD_NUMBER}"

  - wait
  - command: .buildkite/steps/publish.sh
    name: "Publishing :cloudformation: stack"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "templates/mappings.yml;build/aws-stack.json"
    concurrency_group: "aws-stack-publish"
    concurrency: 1

  - wait
  - command: .buildkite/steps/cleanup.sh
    name: "Cleanup"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"