env:
  AWS_STACK_NAME_PREFIX: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
  AWS_STACK_QUEUE_NAME_PREFIX: "testqueue-${BUILDKITE_BUILD_NUMBER}"

steps:
  - name: ":bash: Lint"
    command: .buildkite/steps/lint.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - name: ":packer: Build"
    command: .buildkite/steps/packer.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - name: ":cloudformation: Launch (with stable agent)"
    command: ".buildkite/steps/test.sh stable"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths:
      - "build/*.json"
      - "build/*.yml"

  - name: ":cloudformation: Launch (with beta agent)"
    command: ".buildkite/steps/test.sh beta"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths:
      - "build/*.json"
      - "build/*.yml"

  - wait
  - name: ":buildkite: Instance test (with stable agent)"
    command: "/usr/local/bin/bats --pretty tests/"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}-stable"
      queue: "testqueue-${BUILDKITE_BUILD_NUMBER}-stable"

  - name: ":buildkite: Instance test (with beta agent)"
    command: "/usr/local/bin/bats --pretty tests/"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}-beta"
      queue: "testqueue-${BUILDKITE_BUILD_NUMBER}-beta"

  - wait
  - name: ":cloudformation: :rocket:"
    command: .buildkite/steps/publish.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "templates/mappings.yml;build/aws-stack.json;build/aws-stack.yml"
    concurrency_group: "aws-stack-publish"
    concurrency: 1

  - wait
  - name: "Cleanup"
    command: .buildkite/steps/cleanup.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"