---
env:
  AWS_DEFAULT_REGION: ap-southeast-2

steps:
  - label: ":docker: Clair"
    plugins:
      - ecr#v1.2.0:
          login: true
          account_ids: "644358627301"
      - thedyrt/change-directory#v0.1.1:
          cd: ./ecr-vulnerability-scanning/docker/clair
    commands:
      - "docker build -t 644358627301.dkr.ecr.ap-southeast-2.amazonaws.com/oculo/infrastructure_clair ."
      - "docker push 644358627301.dkr.ecr.ap-southeast-2.amazonaws.com/oculo/infrastructure_clair"
      
  - label: ":docker: Klar"
    plugins:
      - ecr#v1.2.0:
          login: true
          account_ids: "644358627301"
      - thedyrt/change-directory#v0.1.1:
          cd: ./ecr-vulnerability-scanning/docker/klar
    commands:
      - "docker build -t 644358627301.dkr.ecr.ap-southeast-2.amazonaws.com/oculo/infrastructure_klar ."
      - "docker push 644358627301.dkr.ecr.ap-southeast-2.amazonaws.com/oculo/infrastructure_klar"

  - label: ":aws: Services"
    plugins:
      - ecr#v1.2.0:
          login: true
          account_ids: "644358627301"
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::644358627301:role/role-sts-oculo-continuous-integration"
      - thedyrt/change-directory#v0.1.1:
          cd: ./ecr-vulnerability-scanning/sceptre
      - docker-compose#v3.0.0:
          run: infrastructure_tools
