AWSTemplateFormatVersion: '2010-09-09'

Resources:
  RegionalBuildkiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "oculo-buildkite-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PolicyRegionalBuildkiteBucket:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RegionalBuildkiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: 
                - arn:aws:iam::644358627301:root
                - arn:aws:iam::325964603643:root
                - arn:aws:iam::094447749694:root
                - arn:aws:iam::544757391075:root
            Action:
              - s3:Get*
              - s3:Put*
            Resource: 
              - !Join ["", [!GetAtt RegionalBuildkiteBucket.Arn, "/*"]]
          