template_path: .compiled-stack.yaml

stack_name: buildkite

parameters:
  AgentsPerInstance: "3"
  AssociatePublicIpAddress: "true"
  BuildkiteAgentToken: !command_stdout "aws-kms decrypt -i AQECAHjyiQEnGbpdE89VCpDNudW0dSTn64bXL9vH9S/WfG1RPAAAAJIwgY8GCSqGSIb3DQEHBqCBgTB/AgEAMHoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrz4O+LTx5Olt4XEMAgEQgE2xi1ygqLZn1S0UUIfk2qxI1/AtywDw6baFLZ3Upf0cOLm3I44ZDYI1F0RW+vg2mYJ2jKb8yUNeDSUwz+uXdy0w5SAUsHHe2qi6aBtOqw=="
  BuildkiteAgentRelease: stable
  BuildkiteAgentTimestampLines: "false"
  BuildkiteOrgSlug: oculo-1
  BuildkiteQueue: default
  CostAllocationTagName: aws:createdBy
  CostAllocationTagValue: buildkite-elastic-ci-stack-for-aws
  ECRAccessPolicy: poweruser
  EnableCostAllocationTags: "false"
  EnableDockerExperimental: "false"
  EnableDockerLoginPlugin: "true"
  EnableDockerUserNamespaceRemap: "true"
  EnableECRPlugin: "true"
  EnableSecretsPlugin: "true"
  ImageId: !oculo_ami_id '*Oculo Buildkite Server*'
  InstanceCreationTimeout: PT5M
  InstanceRoleName: buildkite-instance-role
  InstanceType: r4.large
  KeyName: development-au-oct-18
  ManagedPolicyARN: arn:aws:iam::544757391075:policy/BuildkitePolicy,arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
  MaxSize: "5"
  MinSize: "2"
  RootVolumeSize: "250"
  ScaleCooldownPeriod: "300"
  ScaleDownAdjustment: "-1"
  ScaleDownPeriod: "1800"
  ScaleUpAdjustment: "1"
  SecretsBucket: oculo-buildkite-secrets
  SpotPrice: "0.045"
  SleepyTime: !timestamp_from_local 18:45
  BreakfastTime: !timestamp_from_local 08:15
