
Resources:
  AgentScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseAutoscaling
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: { Ref: AgentAutoScaleGroup }
      Cooldown: 300
      ScalingAdjustment : { Ref: ScaleUpAdjustment }

  AgentScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseAutoscaling
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: { Ref: AgentAutoScaleGroup }
      Cooldown: 300
      ScalingAdjustment: { Ref: ScaleDownAdjustment }

  AgentUtilizationAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Condition: UseAutoscaling
   Properties:
      AlarmDescription: Scale-up if ScheduledJobs > 0 for 1 minute
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ { Ref: AgentScaleUpPolicy } ]
      Dimensions:
        - Name: Queue
          Value: { Ref: BuildkiteQueue }
      ComparisonOperator: GreaterThanThreshold

  AgentUtilizationAlarmLow:
   Type: AWS::CloudWatch::Alarm
   Condition: UseAutoscaling
   Properties:
      AlarmDescription: Scale-down if UnfinishedJobs == 0 for N minutes
      MetricName: UnfinishedJobsCount
      Namespace: Buildkite
      Statistic: Maximum
      Period: { Ref: ScaleDownPeriod }
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ { Ref: AgentScaleDownPolicy } ]
      Dimensions:
        - Name: Queue
          Value: { Ref: BuildkiteQueue }
      ComparisonOperator: LessThanOrEqualToThreshold

  SpotFleetScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxSize
      MinCapacity: !Ref MinSize
      ResourceId: "spot-fleet-request/$(SpotFleet)"
      RoleARN: !GetAtt [SpotFleetIAMRole, Arn]
      ScalableDimension: 'ec2:spot-fleet-request:TargetCapacity'
      ServiceNamespace: 'ec2'

  FleetUpPolicy:
    Type : "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: FleetUpPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref SpotFleetScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: '1500'
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 10
            MetricIntervalLowerBound: 0
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 10
            ScalingAdjustment: 1

