Resources:
  MetricsStack:
    Condition: CreateMetricsStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/buildkite-cloudwatch-metrics-publisher/master/cloudwatch-metrics-publisher.json
      Parameters:
        BuildkiteApiAccessToken: !Ref BuildkiteApiAccessToken
        BuildkiteOrgSlug: !Ref BuildkiteOrgSlug
        KeyName: !Ref KeyName
        QueueName: !Ref BuildkiteQueue
        PollInterval: 15s
        VpcId: !If [
          "CreateVpcResources",
          !Ref Vpc,
          !Ref VpcId
        ]
        Subnets: !If [
          "CreateVpcResources",
          !Join [ ",", [!Ref Subnet0, !Ref Subnet1]],
          !Join [ ",", !Ref Subnets ]
        ]
      Tags:
        - Key: Role
          Value: buildkite-metrics
        - Key: Name
          Value: buildkite-metrics
