AWSTemplateFormatVersion: '2010-09-09'

Resources:
  BuildkiteSecretsBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "oculo-services-buildkite-secrets"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PolicyBuildkiteSecretsBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BuildkiteSecretsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: arn:aws:iam::644358627301:role/buildkite-instance-role
            Action:
              - s3:Get*
              - s3:Put*
            Resource: !Sub "arn:aws:s3:::${BuildkiteSecretsBucket}"
          