AWSTemplateFormatVersion: "2010-09-09"
Description: "Buildkite SSH Access to Packer Build boxes"

Parameters:
  VpcId:
    Type: String
    Description: VPC that security group will reside in
    Default: ""

Resources:
  BuildkiteSSHToPacker:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to agents
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-packer-ssh-security-group"
      - Key: ApplyToPackerBuilder
        Value: "true"

  PackerSshSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt BuildkiteSSHToPacker.GroupId
      CidrIp: "0.0.0.0/0"
      #SourceSecurityGroupId: !If [ CreateSecurityGroup, !GetAtt SecurityGroup.GroupId, !Ref SecurityGroupId ]
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
